### ISSUE TITLE
Need case sensitive search

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#17]
Case sensitive search is DEFINITLY needed.  Perhaps something like:

-Smystring$

In other words, if the "S" command has a negative argument, use case sensitive search, etc.

Thanks!

**Comment by rhaberkorn** [comment]
Agreed. It's on my TODO list for ages. But `-S` won't do. That's already taken for a backwards search. I think classic TECO had some special characters at the beginning of the search string as a modifier?

**Comment by blakemcbride** [comment]
I think it used a flag.  <code>-1^X</code>

**Comment by blakemcbride** [comment]
I checked.  Regular TECO uses:

|  |  |
|-----------------|-----------------|
| -1^X	|	case sensitive search |
| 0^X	|	case insensitive search |

Once you execute the command, all searches work the set way until you change the mode.

**Comment by rhaberkorn** [comment]
Thanks. I am going to implement ^X soon. I was keeping ^X free for that purpose. I was thinking about repurposing it as the "cut to register" command, but that's likely going to be `@X` instead.

**Comment by rhaberkorn** [comment]
In SciTECO you can now write `-^X` as well instead of `-1^X`. Also, the search mode flag is local to the macro frame, so its current state will not break macros, written under the assumption of the opposing mode.
The same has been done with radix (^R), as changing the radix would break practically all macros, which assume decimal.

Internally, both the search mode and radix are mapped to the *local* Q-Registers `^X` and `^R`, so you can also use the Q-Register stack to change them temporarily.
