### ISSUE TITLE
Horizontal scrolling jumps

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#23]
Not a problem.  A preference.

When displaying very long lines, the display cuts the line short when the screen length is hit.  Good.  That's the way I like it.

If you try to scroll horizontally past the max screen width, the screen shifts horizontally so that the long line can be seen.  In general, I like this.  However, I'd rather it shift one character at a time rather than the larger block shift that it does.  The reason is that when it does  a large horizontal shift your eye has a hard time syncing with the change.  It takes a moment to see where you are.  If, however, it shifts horizontally one character at a time, it is easy to follow what is going on.  Your mind doesn't get momentarily lost.

I realize this is just a personal preference.  Perhaps there can be a configuration option.

Thanks!

**Comment by rhaberkorn** [comment]
This is already configurable in great detail thanks to Scintilla, see [SCI_SETXCARETPOLICY](https://scintilla.org/ScintillaDoc.html#SCI_SETXCARETPOLICY).

For instance to scroll by one character instead of "jumping", try 
`0ESSETXCARETPOLICY$$$` (`$` typed with Escape of course).
If you would like the cursor to see a bit of the line following the cursor, set a strict "slop" value, e.g. 10 characters: `10,(1#4)ESSETXCARETPOLICY$$$`

You can add these statements in `~/.teco_ini`  some where under the `!add!` label in the ED hook macro (stuff that gets executed when adding a new buffer to the ring).

Please close this ticket if your question has been answered.

**Comment by blakemcbride** [comment]
Thanks!  I apologize for using this issue platform to find out about documented facilities.

**Comment by rhaberkorn** [comment]
> Thanks! I apologize for using this issue platform to find out about documented facilities.

No problem. You can also open [discussions](https://github.com/rhaberkorn/sciteco/discussions).

**Comment by rhaberkorn** [comment]
> set a strict "slop" value, e.g. 10 characters

The value is actually in _pixels_, which just happens to coincide with characters in the Curses UI. If you want a value that works with both the Curses and GTK UIs, you could write: `33ESTEXTWIDTH$9$*10,(1#4)ESSETXCARETPOLICY$$$`
