### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aksr** [rhaberkorn/sciteco#26]
TECO *true* beginner here, anyway:

1. run `sciteco`
2. type, for example, `n=`
3. ***Segmentation fault***

(Version: r1060.0f740ee)

**Comment by rhaberkorn** [comment]
Nice catch. Should be fixed now in HEAD. I retriggered a [nightly build](https://github.com/rhaberkorn/sciteco/releases/tag/nightly) in case you would like to try one of these.

Let me know of any other problems you encounter. Or ask questions in the "Discussions" section. Or write in the alt.lang.teco newsgroup if you're old-school.

PS: `N=` is actually nonsensical on a fresh buffer. It does not print anything (`=` command), but instead starts a search across all buffers for the string `=`.

**Comment by rhaberkorn** [comment]
> You could/should make an _**elaborate**_ video in which you demonstrate
> (1) speed, (2) efficiency, and some interesting use-cases as _to awake a breadth of possibilities_ with this way of editing.

I was hoping to attract some sort of community and that somebody else would do that for me eventually. I am not really into video editing.

> PS: After discovering a brilliant! SNOBOL4, I'm wondering what else got lost in time...

I also had that SNOBOL-phase in my life. ;-)

**Comment by rhaberkorn** [comment]
> Just your regular workflow, should be interesting enough...

Agreed. Will see to it.

> I was hoping it would be **just** a phase by me.

You are doing some serious work in SNOBOL4? I was put off by its goto-based flow control. Never wrote more than a few scripts. (Object) Icon is in principle much more viable, but you know how it is: You can use obscure languages only for your own private projects and even there you have to weigh availability of the software and libraries against your own wishes.

**Comment by rhaberkorn** [comment]
I thought about writing the "Monkey on a typewriter"-test for SciTECO in CSNOBOL4, but it doesn't cut it either. I need both read-with-timeout (select(), poll()...) and UTF-8 support. That alone restricts me to more mainstream languages like Python or Perl. Perhaps Lua 5.3 with lposix or LuaJIT. GNU APL actually has select(). A good chance to put another obscure language into the SciTECO repo! ;-)

**Comment by rhaberkorn** [comment]
> You wanted to script something very fast (usually to elude something very boring), and it's there, it works. If we were honest, much of everyday code which we made and/or use, is not (very) pretty and we don't care since we are not (usually) publishing it and we don't care enough to polish it.

Well actually, at the same time, almost every piece of software you will write, is buggy and will have to be fixed. So, "write once" software doesn't _really_ exist. I had my problems understanding and debugging some of my SNOBOL scripts even very simple ones. Nothing would prevent you from supporting both GOTO and structured programming constructs. I mean theoretically, you can restrict yourself to a certain style of GOTO-programming, that is in effect structured, but you never do that.

> I think Iain McGilchrist (The Master and His Emissary) would agree with him, and, TBH, I would, too, now. (I wonder what (book?) sources Emmer used to get to this conclusion.) I turned off puritan inside me when I saw (and felt) what is the price.

You will like Icon as they took the backtracking algorithm and generalized it.
I always wondered how a pure backtracking-based language would look like. It needs to undo side effects during backtracking. Languages like SNOBOL, Icon or Prolog restrict that to very small parts of the program state (like the pointer into the matched string). For more, you would need... something like SciTECO's undo stack! For a long time I therefore have the dream of adding SNOBOL-style backtracking to SciTECO in a special execution mode, that essentially eliminates the difference between pattern matching constructs and all regular commands. Imagine the possibilities! Transform your text _while_ you are matching it...

> I love C still, but my love is not exclusive anymore. ;)

I use C often because it is kind of the lingua franca of computing. It's everywhere, it's portable, it's rock solid, it has direct access to all OS APIs and the largest number of libraries without any wrappers; and usually it's more flexible than people think. C++ would also tick these boxes due to its C compatibility (more or less), but is just a horrible language. Take SciTECO, sure I could have written it in a number of more hipster-languages like Rust or Zig or Go or whatever, but at the cost of restricting portability, of struggling with poorly written wrappers, with increased memory usage. And some features like it's memory limiting would be impossible at least without some C. I sometimes fear other languages, yes, I fear the bloat, the increased overall complexity of the system. If it's not some kind of experiment or optional script, I'll usually write in C.

> BTW, what do you think about sams editor language?

I suppose you mean structural regexp? Can't really say much about that, as I never fully understood it. As a UI, these editors are of course interesting and I appreciate that they tried things differently. I personally do not like heavy mouse-centered approaches, though.

> I'm sorry for this long, uncalled-for response.

Never mind, I like this kind of exchange as well. Although private mail or alt.lang.teco, would probably be a better place for it.

**Comment by rhaberkorn** [comment]
With backtracking constructs, macros turn into named grammar rules. And they will of course take arguments and return values, effectively turning them into feature grammars. Actually every branch can of course return values as well. Logical programming should also be possible that way. Or Icon-style generators. It will be _extremely_ powerful. With the right design, it could be useful in interactive editing as well.

**Comment by rhaberkorn** [comment]
Thinking some more about it, I realize it's not that easy. Actually, successful backtracking branches *must not* pop the backtracking stack as it may be necessary to back track into them later on and try another branch (unless we have already reached `'` of course). If you use macros as "named" grammar rules, it must be possible to backtrack into already completed macro frames as well. This is not possible in the current design, but may be possible once I manage the macro frames more explicitly (which is planned anyway). The devil lies in the details...
