### ISSUE TITLE
Closing a loop twice causes sciteco to crash

### ISSUE THREAD

**Issue by th12h** [rhaberkorn/sciteco#3]
Compiled on arch linux 32 bit. Ncurses UI.
Anything along the lines of `n<cmds>>` will crash sciteco. Impossible loops in general (ie: `2<c>` in an empty buffer) cause severe problems ranging from crashes to hangs and out of control memory leaks.

`*5<c> **                                                                          
        ERROR:parser.cpp:861:virtual SciTECO::State* SciTECO::StateStart::custom(gchar): assertion failed: (expressions.pop_op() == Expressions::OP_LOOP)
                                                                      zsh: abort (core dumped)  sciteco .xinitrc`

Core generated with gdb at https://u.teknik.io/vjpe46.5017

Edit: thanks, markdown

**Comment by rhaberkorn** [comment]
Hello and thanks for your bug report!

I can confirm the first issue. The most simple test case is:

    $ sciteco -e '>'

I cannot confirm the second bug (impossible loops crash).
E.g. `sciteco -e '5<c>'` and `sciteco -e '@i/hello/ 2r 5<c>'` all work as expected here on my system (a very odd system, I have to add) by throwing SciTECO errors. It also works in interactive mode - SciTECO does not allow you to type the "c" or ">" since these characters would result in errors.
Can you give a test case, preferably with `sciteco -e` and tell me your compile flags? I.e. did you build with `-O0` or `-O2`?

I cannot properly analyze the core dump you sent. I need at least the exact sciteco binary that caused that dump and the Git commit. Best is to send an archive of the entire source tree including the binary. Also make sure you've compiled that binary with `-g` when submitting core dumps. Nevertheless, a test case is always better than a core dump.

**Comment by rhaberkorn** [comment]
Valgrind is still pretty much useless here on my Linaro Ubuntu (running on ARM) as it reports thousands of bogus errors.
Will run it on a PC if you insist that there's a memleak.

**Comment by th12h** [comment]
This is with 4624eebd7838ef948b9a17a2f29005d0e4b1d8e4 (compiled with -O2) on an odd system (64 bit processor, 32 bit kernel, long story). The hang and leak only happens with the ncurses ui (urxvt, xterm, uxterm, vte tested), so a batch mode test case would be pointless.

It fails with `terminate called after throwing an instance of 'St9bad_alloc' what():  std::bad_alloc` when killed with signal 9 (`<nc>` at the last char of a buffer or in an empty buffer). Only the useless, but easy to accidentally type `<infinite loop>` form is affected. It's as if sciteco does not care if a loop (at its simplest, `<istr$>`) does not terminate, and does not successfully determine if the cursor will move beyond the buffer if it is already at the end and the movement command is inside an infinite loop, resulting in the bug. Several sessions have been lost to loop-related typos.

Binary from 4624eebd7838ef948b9a17a2f29005d0e4b1d8e4, recompiled with -g this time (whoops): https://u.teknik.io/3E7UsK
Binary from latest:
https://u.teknik.io/rjvkDH

The full core from the second issue (via gcore) is 1.6 gigabytes in size, and that's as small as I can get it. I'm afraid you'll have to generate it yourself. Sorry if I can't help any more.

**Comment by rhaberkorn** [comment]
Hi!
I think I know what happens here and it is actually currently the defined behaviour.
The infinite loop is not useless at all - it is a commonly used structure if the loop termination condition is not a counter. Just like you would use `for (;;)` with some condition that results in `break;` in C, you can use the `;` command to break out of an infinite loop in SciTECO. E.g. `<@FS/foo/bar/;>` would replace all occurrences of `foo` with `bar`.

If you don't have a loop termination condition, the loop iterations will accumulate "undo tokens" until you run out of memory. In interactive mode, any command executed will result in memory allocations. This is absolutely necessary, so that SciTECO can undo changes on rubout. There would be a memleak if it ran out of memory in batch mode - an infinite loop in batch mode should run infinitely with constant memory usage. SciTECO tries to recover from OOMs, but it cannot be guaranteed to work. Usually this is not a problem since you can interrupt the loop (actually any blocking command) by pressing CTRL+C if you notice that it does not terminate. Therefore, I did not consider this an urgent issue - I never have problems with it.

It is hard for a program to be completely immune to such OOM issues. If you allocate memory from the heap depending on usage, you can run out of (virtual) memory and it is impossible to properly handle that. Most programs just abort() on OOMs. However SciTECO could reserve some fixed amount of memory on startup and use its own memory manager - but there is memory usage that is not controlled by SciTECO (e.g. in Scintilla). SciTECO could also limit the amount of undo tokens generated per character. This - if properly set up - should prevent the infinite-loop issue in most cases but cannot completely eradicate it. It's already on my `TODO` list. Perhaps I'll do it today!

**Comment by rhaberkorn** [comment]
Let me give another example: A web server can never guarantee that it does not run out of memory or (socket) resources when accepting and handling connections (unlimited or fixed maximum number of connections). Any heuristic applied to prevent these OOM conditions (which are usually fatal) are insufficient. Web servers therefore commonly have __user configurable__ limits on the number of incoming connections. They have reasonable defaults for these limits - but depending on the overall system, they might not prevent OOMs or out-of-socket issues. It is then the administrators task to tweak the server config to accomodate the use case.

With the undo-token-per-char limit in SciTECO it would be similar. SciTECO would start up with a reasonable default that will work in 99% of the cases, but you may have to tweak that limit if you're especially low on memory or have to execute very long running loops or macros - the setting will indirectly limit the number of commands that can be executed by a loop or macro call. Even then, OOMs may still happen, e.g. because it limits the undo-tokens per character instead of the overall number of tokens or you happen to have some Java program running that eats most of your memory :D

**Comment by rhaberkorn** [comment]
Ok, I solved this differently. Instead of introducing an undo token per char limit, I introduced a memory limit on the size of the entire undo stack (in bytes). This is both more secure as it limits the bulk of memory used by the editor and easier to tweak.

The default is 500mb. So if you can spare that much memory for SciTECO in extreme situations, everything should be alright. If not you can tweak the value with the `2EJ` command in your profile (see `sample.teco_ini`).

**Comment by rhaberkorn** [comment]
By the way, this will fix the `<istr$>` example you gave.
`<c>` at the end of the buffer (or anywhere in the buffer) should never have provoked that issue as the loop will always terminate rather quickly. SciTECO will not accept the `>` character as it would move you off-page.
`<nc>` is not a complete SciTECO command at all - `N` starts a search-in-all-buffers command and must be terminated with <ESC>. `<nc$>` would be a "true" infinite loop, though that should be "fixed" by my last commit.
