### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by blakemcbride** [rhaberkorn/sciteco#4]
Really nice to see stuff done with Teco!!

Some things I noticed:

1.  Really hate the extra space at the beginning of each line.

2.  EX should save and exit

3.  B= should be zero, not one.

4.  Not sure what I typed but I got a syntax error and was utterly unable to get past it.  I tried BS, $$, ^C, etc..  Nothing would get me out of that condition.  I had to kill the process.

5.  I understand having to do -L to go back a line is tedious, but I am not sure re-mapping B is the best answer.  Mapping the cursor keys is.

I only spent about 5 minutes with it after building it.  Again, I am really excited to see work done wit Teco!!

Thanks!!

Blake

**Comment by rhaberkorn** [comment]
Hello Blake,

nice to see that there's a new user :-). Regarding your points:

1. This is entirely configurable by Scintilla (the editor component). SciTECO allows you to issue Scintilla configuration commands. You will want to do this in the ED hook of your profile under "!add!". Copy the `sample.teco_ini` profile from the installation to `~/.teco_ini` if you haven't done so already. Replace the 4 lines below "! Set up margins !" with the following to disable all margins:

    0,0ESSETMARGINWIDTHN$$$
    0,1ESSETMARGINWIDTHN$$$
    0,2ESSETMARGINWIDTHN$$$

2. SciTECO is not classic TECO, it is more similar to Video TECO. It supports an arbitrary number of buffers. Which buffers should it save? How to discard all changes easily? I found the current behaviour (inspired by Video TECO) sufficient and handy. E.g. you can call `-ex$$` to exit unconditionally like Vi's `:q!`.

3. B is equivalent to -L in SciTECO. Again this was inspired by Video TECO. B as 0 makes no sense for an editor that loads entire files into memory. It would be a waste of a precious one-letter command - these are very scarce you know ;-). `=` will show 1, since currently 1 is implied for `=` if the argument is missing. I found that there is no benefit in implying values for `=` so I will change that sooner or later.

4. You probably ended up in an infinite loop. These can be interrupted by ^C. At least on Unix+Curses. For other platforms, I still have to separate the UI/input from code execution via threads (not as easy as it sounds). You can also send the INT signal to the process which has the same effect. Also, I found recently that ^C is broken, even on Unix. Will fix that soon. It's high priority. If you let the loop run, SciTECO will also hit its undo-stack-memory-limit and recover eventually - but this can take some time.

5. I use B frequently. It's also easy to remember (B as in backwards). Cursor keys are also supported. Check out function key macros in the manual. You will only have to uncomment the `0,64ED` statement in your profile.

Best regards,
Robin

**Comment by blakemcbride** [comment]
I think ex$$ should save all modified buffers and exit.

Even after you fix the ^C problem (I have on Linux), there is still some sort of infinite loop that it gets stuck on.  This is a separate bug.  I keep getting it when I use ex$$ to save-and-exit like I am used to.

I spent a bunch of time with Video teco over the years.  Every time I tried to use it in a live situation it crashed loosing all of my edits.  I've never been able to reliably duplicate the problem.  I just can't trust it.

Thanks.

Blake

**Comment by rhaberkorn** [comment]
I will consider the `ex$$` behaviour you propose. But I'm still skeptical as all other text editors will not just save all changes when you try to close them. Instead they usually ask you whether to save all changes or discard them. The current behaviour of `ex` ensures that you can decide whether to save the modified buffers or discard all changes in case you just forgot about the modified buffers.
Also, the exit-time behaviour is already configurable in SciTECO and can be adapted to your needs easily. E.g. if you add something like `0U.b EJ<%.bU*:Q*">EW$'>` to your "quit" hook in register ED after `M[session.save]`, SciTECO will save all buffers on exit - but you will still have to exit with `-ex$$` if you have modified buffers and there is no way to discard all changes. You could also simply define a macro "EX" as follows:

    @^U#EX{
      0U.b EJ<%.bU*:Q*">@EW//'>
      EX
    }

And exit with `m#ex$$`.

Regarding the infinite loop on `ex$$`. I have never experienced this and will need more information about what you've done to provoke it. The only code executed after `ex$$` should be the "quit" hook which calls `M[session.save]` in `sample.teco_ini`. Perhaps you should try to remove the SciTECO standard library and reinstall it (I frequently change it):

    sudo rm -rf /usr/local/share/sciteco
    sudo make install

It is also possible that you did a mistake while adapting the margin configuration in the ED-hook. Could you post your `~/.teco_ini` or add it as a Gist for me to have a look at it, please?

**Comment by rhaberkorn** [comment]
Regarding the ^C bug, I'm currently waiting for feedback by the ncurses maintainers:
http://lists.gnu.org/archive/html/bug-ncurses/2015-06/msg00011.html

I do know a solution that works with ^C (terminal initialization as in SciTECO v0.5), but I'm not happy with the old implementation either.

I will probably have to patch Scinterm to get this working properly and across platforms. This will take some time to implement I'm afraid.

**Comment by rhaberkorn** [comment]
Regarding your original point 4, I overlooked that you've written about a prior syntax error.
It seems more likely that instead of an infinite-loop, you accidentally pressed ^G. This toggles the immediate editing command modifier. If it is activated, backspace will not rub-out but rub-in from a previously rubbed-out command line (i.e. Redo). This is probably what happened. If it happens again, just press ^G again. If you use the standard function key definitions from `fnkeys.tes`, you can also press Shift+Backspace to do a backspace-operation with inversed modifier.
Yes I know, SciTECO is not trivial to master...

**Comment by rhaberkorn** [comment]
I think I addressed all the issues you brought up, so I'm finally closing this ticket.

- Loops are reliably interruptable by pressing ^C in the GTK+, ncurses/Unx, ncurses/win32 and PDcurses/win32 frontends
- margins are completely disabled now by default (e.g. when you start up with `sciteco --no-profile`) but are set in the template `teco_ini.sample`. This is easy to comment out or to remove.
- `=` requires an argument now and fails otherwise
- exiting with saving all modified buffers is possible using `:EX$$` now. I'm still uncertain whether to make the default behaviour (without `:`) configurable. But even if you prefer the current implementation - as I do - it is still useful to have something like `:EX`. If you still find this too long to type, consider adding a function key macro that does this on a single key-press.
- I could never reproduce the other "hangs" on exit you described and I'm assuming this was the ^G behaviour I explained.

**Comment by rhaberkorn** [comment]
I must let `:EX` fail for modified unnamed buffers since they cannot be saved without providing a name. But this will hardly ever be a problem.

btw. There is already the `CLOSE` function key macro in `fnkeys.tes` which calls `EX` and can be adapted at will. This is meant as a pseudo key handler for real GUIs like GTK+ in order to configure the behaviour of the window's "close" button; but it can just as well be used on ncurses if you remap some key in your terminal emulator or xkb.
